# Generated by Django 3.0.5 on 2020-04-17 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 5, 24, 36, 887947, tzinfo=utc)),
        ),
    ]
